"""first migrate

Revision ID: 1ebb4846beb4
Revises: 
Create Date: 2020-12-02 19:59:36.081028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebb4846beb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Credit',
    sa.Column('Credit_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('credit_name', sa.String(length=255), nullable=False),
    sa.Column('credit_num', sa.Integer(), nullable=False),
    sa.Column('expire', sa.Date(), nullable=False),
    sa.Column('security_code_hash', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Credit_id')
    )
    op.create_table('ShippingAddress',
    sa.Column('ShippingAddress_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name_kana', sa.String(length=255), nullable=False),
    sa.Column('first_name_kana', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('prefecture', sa.String(length=64), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=False),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('ShippingAddress_id')
    )
    op.create_table('User',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('user_cord', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('picture_path', sa.Text(), nullable=False),
    sa.Column('prof_comment', sa.Text(), nullable=True),
    sa.Column('defalt_ShippingAddress_id', sa.Integer(), nullable=True),
    sa.Column('defalt_pay_way', sa.Integer(), nullable=False),
    sa.Column('defalt_Credit_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['defalt_Credit_id'], ['Credit.Credit_id'], ),
    sa.ForeignKeyConstraint(['defalt_ShippingAddress_id'], ['ShippingAddress.ShippingAddress_id'], ),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_user_cord'), 'User', ['user_cord'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=False)
    op.create_table('UserTempToken',
    sa.Column('UserTempTokenToken_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.PrimaryKeyConstraint('UserTempTokenToken_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_UserTempToken_token'), 'UserTempToken', ['token'], unique=True)
    op.create_table('Address',
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('prefecture', sa.String(length=64), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=False),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Address_id')
    )
    op.create_table('MailResetToken',
    sa.Column('MailResetToken_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('MailResetToken_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_MailResetToken_token'), 'MailResetToken', ['token'], unique=True)
    op.create_table('PasswordResetToken',
    sa.Column('PasswordResetToken_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('PasswordResetToken_id')
    )
    op.create_index(op.f('ix_PasswordResetToken_token'), 'PasswordResetToken', ['token'], unique=True)
    op.create_table('Sell',
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('sell_title', sa.String(length=255), nullable=False),
    sa.Column('key1', sa.String(length=255), nullable=False),
    sa.Column('key2', sa.String(length=255), nullable=False),
    sa.Column('key3', sa.String(length=255), nullable=False),
    sa.Column('sell_comment', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('item_picture_path', sa.Text(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('item_state', sa.Integer(), nullable=False),
    sa.Column('postage', sa.Integer(), nullable=False),
    sa.Column('send_way', sa.Integer(), nullable=False),
    sa.Column('consignor', sa.String(length=64), nullable=False),
    sa.Column('schedule', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('deal_status', sa.Integer(), nullable=False),
    sa.Column('sell_flg', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_sent', sa.Boolean(), nullable=False),
    sa.Column('has_got', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Sell_id')
    )
    op.create_table('UserConnect',
    sa.Column('UserConnect_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['from_user_id'], ['User.User_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('UserConnect_id')
    )
    op.create_table('UserInfo',
    sa.Column('UserInfo_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name_kana', sa.String(length=255), nullable=False),
    sa.Column('first_name_kana', sa.String(length=255), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('UserInfo_id')
    )
    op.create_table('Buy',
    sa.Column('Buy_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('pay_way', sa.Integer(), nullable=False),
    sa.Column('Credit_id', sa.Integer(), nullable=False),
    sa.Column('ShippingAddress_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['Credit_id'], ['Credit.Credit_id'], ),
    sa.ForeignKeyConstraint(['Sell_id'], ['Sell.Sell_id'], ),
    sa.ForeignKeyConstraint(['ShippingAddress_id'], ['ShippingAddress.ShippingAddress_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Buy_id')
    )
    op.create_table('DealMessage',
    sa.Column('DealMessage_id', sa.Integer(), nullable=False),
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['Sell_id'], ['Sell.Sell_id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['User.User_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('DealMessage_id')
    )
    op.create_table('Likes',
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['Sell_id'], ['Sell.Sell_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Sell_id', 'User_id')
    )
    op.create_table('PostMessage',
    sa.Column('PostMessage_id', sa.Integer(), nullable=False),
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['Sell_id'], ['Sell.Sell_id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('PostMessage_id')
    )
    op.create_table('Rating',
    sa.Column('Rating_id', sa.Integer(), nullable=False),
    sa.Column('Sell_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rating_message', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('update_at >= create_at'),
    sa.ForeignKeyConstraint(['Sell_id'], ['Sell.Sell_id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['User.User_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Rating_id')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rating')
    op.drop_table('PostMessage')
    op.drop_table('Likes')
    op.drop_table('DealMessage')
    op.drop_table('Buy')
    op.drop_table('UserInfo')
    op.drop_table('UserConnect')
    op.drop_table('Sell')
    op.drop_index(op.f('ix_PasswordResetToken_token'), table_name='PasswordResetToken')
    op.drop_table('PasswordResetToken')
    op.drop_index(op.f('ix_MailResetToken_token'), table_name='MailResetToken')
    op.drop_table('MailResetToken')
    op.drop_table('Address')
    op.drop_index(op.f('ix_UserTempToken_token'), table_name='UserTempToken')
    op.drop_table('UserTempToken')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_user_cord'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('ShippingAddress')
    op.drop_table('Credit')
    # ### end Alembic commands ###
