"""first migrate

Revision ID: 934e0135daa7
Revises: 
Create Date: 2020-08-22 01:22:47.607471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934e0135daa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('picture_path', sa.Text(), nullable=True),
    sa.Column('prof_comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=False)
    op.create_table('Address',
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('prefecture', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Address_id')
    )
    op.create_table('PasswordResetToken',
    sa.Column('PasswordResetToken_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), server_default='<function uuid4 at 0x7fe210eeaaf0>', nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('PasswordResetToken_id')
    )
    op.create_index(op.f('ix_PasswordResetToken_token'), 'PasswordResetToken', ['token'], unique=True)
    op.create_table('UserInfo',
    sa.Column('UserInfo_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name_kana', sa.String(length=255), nullable=True),
    sa.Column('first_name_kana', sa.String(length=255), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('UserInfo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserInfo')
    op.drop_index(op.f('ix_PasswordResetToken_token'), table_name='PasswordResetToken')
    op.drop_table('PasswordResetToken')
    op.drop_table('Address')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
