"""add ShippingAddress,Credit

Revision ID: e350f0eb6e89
Revises: 934e0135daa7
Create Date: 2020-10-21 00:22:19.964021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e350f0eb6e89'
down_revision = '934e0135daa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Credit',
    sa.Column('Credit_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('credit_name', sa.String(length=255), nullable=True),
    sa.Column('security_code', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('Credit_id')
    )
    op.create_table('ShippingAddress',
    sa.Column('ShippingAddress_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name_kana', sa.String(length=255), nullable=True),
    sa.Column('first_name_kana', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('prefecture', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('address3', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.User_id'], ),
    sa.PrimaryKeyConstraint('ShippingAddress_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShippingAddress')
    op.drop_table('Credit')
    # ### end Alembic commands ###
